# Dockerfile for PostgreSQL Database

# Use the official image from the dockerhub
FROM postgres:13

# The following environment variables are optional

# Specify the user who will run the Postgres instance
ENV POSTGRES_USER postgres

# Specify the password for the Postgres user
ENV POSTGRES_PASSWORD secret

# Specify the name of the database to be created on image startup
ENV POSTGRES_DB myappdb
